from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 527)
        MainWindow.setMinimumSize(QtCore.QSize(668, 527))
        MainWindow.setMaximumSize(QtCore.QSize(668, 527))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.lineEdit_request = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_request.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_request.setText("")
        self.lineEdit_request.setObjectName("lineEdit_request")
        self.horizontalLayout_5.addWidget(self.lineEdit_request)
        self.pushButton_find = QtWidgets.QPushButton(self.widget)
        self.pushButton_find.setMaximumSize(QtCore.QSize(16777215, 23))
        self.pushButton_find.setObjectName("pushButton_find")
        self.horizontalLayout_5.addWidget(self.pushButton_find)
        self.pushButton_clear = QtWidgets.QPushButton(self.widget)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(16777215, 23))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_5.addWidget(self.pushButton_clear)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_map = QtWidgets.QRadioButton(self.widget)
        self.radioButton_map.setMaximumSize(QtCore.QSize(16777215, 17))
        self.radioButton_map.setChecked(True)
        self.radioButton_map.setObjectName("radioButton_map")
        self.horizontalLayout.addWidget(self.radioButton_map)
        self.radioButton_sat = QtWidgets.QRadioButton(self.widget)
        self.radioButton_sat.setMaximumSize(QtCore.QSize(16777215, 17))
        self.radioButton_sat.setChecked(False)
        self.radioButton_sat.setObjectName("radioButton_sat")
        self.horizontalLayout.addWidget(self.radioButton_sat)
        self.radioButton_hybrid = QtWidgets.QRadioButton(self.widget)
        self.radioButton_hybrid.setMaximumSize(QtCore.QSize(16777215, 17))
        self.radioButton_hybrid.setObjectName("radioButton_hybrid")
        self.horizontalLayout.addWidget(self.radioButton_hybrid)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.labelMap = QtWidgets.QLabel(self.splitter)
        self.labelMap.setMinimumSize(QtCore.QSize(650, 450))
        self.labelMap.setMaximumSize(QtCore.QSize(650, 450))
        self.labelMap.setText("")
        self.labelMap.setObjectName("labelMap")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_address = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_address.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_address.setText("")
        self.lineEdit_address.setReadOnly(True)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout_2.addWidget(self.lineEdit_address)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_wo_index = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_wo_index.setMaximumSize(QtCore.QSize(16777215, 17))
        self.radioButton_wo_index.setObjectName("radioButton_wo_index")
        self.horizontalLayout_3.addWidget(self.radioButton_wo_index)
        self.radioButton_with_index = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_with_index.setMaximumSize(QtCore.QSize(16777215, 17))
        self.radioButton_with_index.setChecked(True)
        self.radioButton_with_index.setObjectName("radioButton_with_index")
        self.horizontalLayout_3.addWidget(self.radioButton_with_index)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Запрос:"))
        self.pushButton_find.setText(_translate("MainWindow", "Искать"))
        self.pushButton_clear.setText(_translate("MainWindow", "Сброс"))
        self.radioButton_map.setText(_translate("MainWindow", "Схема"))
        self.radioButton_sat.setText(_translate("MainWindow", "Спутник"))
        self.radioButton_hybrid.setText(_translate("MainWindow", "Гибрид"))
        self.label_2.setText(_translate("MainWindow", "Полный адрес:"))
        self.radioButton_wo_index.setText(_translate("MainWindow", "Без индекса"))
        self.radioButton_with_index.setText(_translate("MainWindow", "С индексом"))
